### ISSUE TITLE
 Auth0Widget is not defined

### ISSUE THREAD

**Issue by thomas-tran** [auth0/auth0-angular#129]
When I tried to use auth0-angular version 4.0.1 and //cdn.auth0.com/w2/auth0-4.js with angularjs 1.3.6 , requirejs I got this error.  I tried to figure out for a day but did not know what's the issue. Please help to check.

Thanks.
Thomas

**Comment by mgonto** [comment]
Hey there,

[This is an example](https://github.com/auth0/auth0-angular/tree/master/examples/requirejs) that uses `auth0-angular` 4.0.1 with `auth0.js` and `requirejs`.

Let me know if that helps you find out the problem.

Thanks!

**Comment by sidthesloth** [comment]
Hi 
I have got the same problem and i have looked at the example @mgonto has shared but still cannot get a resolution, his is where it fails
if (null != Auth0Widget) {
          throw new Error('Auth0Widget is not supported with this version of auth0-angular' + 'anymore. Please try with an older one');
        }
the Auto0widget is undefined
And the documentation for says that 

auth0-angular depends on either auth0.js or auth0-lock.js.
If you want to use Auth0's beautiful Lock UI, you need to include auth0-lock.js. This lets you configure Title and Icons, but the UI is taken care for you. For all the customization properties, please check out this link
Otherwise, if you'll use a custom UI, you need to include auth0.js.
Which means that if I use custom UI all I need is auth0.js, which I have but still no success.
thanks
sidthesloth

**Comment by RYFN** [comment]
I also see this issue if I use the version of auth0-lock that is pulled in by bower (v7.4.0) instead of //cdn.auth0.com/js/lock-6.js as shown in the example here https://github.com/auth0/auth0-angular/tree/master/examples/widget

**Comment by Zertz** [comment]
Seems like auth0-lock is broken with module loaders in general.

I fixed that issue with Auth0Widget and now I'm investigating why it's not finding Auth0Lock.

**Comment by Zertz** [comment]
@sidthesloth I have a hacky solution for now, see PR #165

**Comment by cyrixmorten** [comment]
I had a similar issue and was unable to use node + browserify to compile. Thought I would share my progress.

1) *Prepare* in package.json I added:

    "dependencies": {
        "auth0-lock": "4.0.4",
        "auth0-lock": "^7.12.3"
    },
    "devDependencies": {
        "brfs": "0.0.8",
        "ejsify": "0.1.0",
        "packageify": "^0.2.0"
     }

as mentioned in the documentation.

2) *Browserify* now I added the following script:

    "build:auth": "browserify ./node_modules/auth0-lock/standalone.js -o ../target/client/js/deps.auth.js"

3) *ERROR* 

    Error: Line 1: Unexpected token < (<path>/client/node_modules/auth0-lock/lib/html/main.ejs) while parsing file: <path>/client/node_modules/auth0-lock/lib/html/main.ejs
        at Stream.end (<path>/client/node_modules/brfs/index.js:39:32)
        at _end (<path>/client/node_modules/brfs/node_modules/through/index.js:61:9)
        at Stream.stream.end (<path>/client/node_modules/brfs/node_modules/through/index.js:70:5)
        at DestroyableTransform.onend (<path>/client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
        at DestroyableTransform.g (events.js:260:16)
        at emitNone (events.js:72:20)
        at DestroyableTransform.emit (events.js:166:7)
        at <path>/client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:934:16
        at doNTCallback0 (node.js:428:9)
        at process._tickCallback (node.js:357:13) 

4) *FIX* after some trial and error I found that modifying the order of which the browserify transformations are applied would allow the compiling to proceed:

`<path>/node_modules/auth0-lock/package.json`

 - Before: 

        "browserify": {
             "transform": [
              "brfs",
              "ejsify",
              "packageify"
             ]
         },

 - After: 

        "browserify": {
             "transform": [
              "ejsify",
              "brfs",
              "packageify"
             ]
         },

5) *Add to index* now adding `deps.auth.js` as dependency works for me and even more importantly, I can yet again run my unit tests .

**Comment by rhinoceraptor** [comment]
If you are using Browserify/Webpack, you have to manually do one of the following:

```window.Auth0 = require('auth0-js')```

```window.Auth0Lock = require('auth0-lock')```

For some reason, I was getting an Angular injector error when it did the check for ```Auth0Widget``` being defined, which was pretty confusing. Then I realized that Auth0.js/Auth0Lock don't attach themselves to ```window``` which was causing the error.

**Comment by cyrixmorten** [comment]
Ok thanks, seems to make sense :-)

Will try it out Monday. Did work around it using cdn links instead but kind
of complicated my junit tests being unable to inject auth.

**Comment by christiannwamba** [comment]
Hi!

Where you able to resolve this issue so I can close?

**Comment by TSteele27** [comment]
I ran into this issue today, and @rhinoceraptor's fix worked for me.

**Comment by yadue** [comment]
Could I ask for fix? It's pretty important when building script from npm via CI, just reorder them please.
