### ISSUE TITLE
Error calling signin after minification.

### ISSUE THREAD

**Issue by aarondandy** [auth0/auth0-angular#143]
After performing JS minification, including auth0-angular.js and auth0.js we get an error when calling signin:

`TypeError: Cannot read property 'parseOptions' of undefined`

After digging around I realized this is due to the function definition of `Auth0` in auth0.js being renamed during our minification process. Looking at the code I see that the function name is used to populate the `lib` property of the config object due to the following lines of code:

https://github.com/auth0/auth0-angular/blob/432573a224fdf151e6063b6a7d4bb202762e5ed4/src/auth0-angular.js#L161
https://github.com/auth0/auth0-angular/blob/432573a224fdf151e6063b6a7d4bb202762e5ed4/src/auth0-angular.js#L201

Would it be possible to provide a value to override the `lib` name, perhaps in the `options` parameter of `init`? Any other ideas or suggestions would be great too.

As a workaround I have a function definition that escapes minification: `function Auth0() { return __auth0Capture.apply(this, arguments); };`

**Comment by mgonto** [comment]
Hey there,

With the [new code](https://github.com/auth0/auth0-angular/blob/master/src/auth0-angular.js#L158-L188) we've implemented a couple days back, that problem should have been solved.

Are you still having the problem with the latest version of `auth0-angular` as well?

Thanks!

**Comment by aarondandy** [comment]
We are using auth0-angular 4.0.1 and are falling into the first condition:
https://github.com/auth0/auth0-angular/blob/432573a224fdf151e6063b6a7d4bb202762e5ed4/src/auth0-angular.js#L161

The name of the function definition for `Auth0` was being mangled which caused issues later during execution. We worked around this by excluding the `Auth0` identifiers from any mangling process.

**Comment by mgonto** [comment]
But we've changed that in the newer version of auth0-angular. That's what I linked in my previous post. Can you try with the newer version?

Thanks!

**Comment by mgonto** [comment]
Hey,

So you're sending a Constructor to the `auth0Angular` init method?

Thanks!

**Comment by aarondandy** [comment]
Yeah, we are sending the Auth0 function/constructor in as we bring it into scope using require.js .

**Comment by mgonto** [comment]
I'll try it out and see if we can fix it without the option. Otherwise, I'll add the option!

Thanks for the bug report!

**Comment by motin** [comment]
Ran into this with the latest minified versions of auth0 libs prescribed in the angularjs guide. When I click login it says:

```
TypeError: Cannot read property 'parseOptions' of undefined
    at getInnerLibraryConfigField (http://cdn.auth0.com/w2/auth0-angular-4.js:150:55)
    at Object.$get.auth.signin (http://cdn.auth0.com/w2/auth0-angular-4.js:349:23)
    at Scope.service.login (http://localhost:9000/scripts/angular-frontend.js:34:18)
    at fn (eval at <anonymous> (http://localhost:9000/bower_components/angular/angular.js:13231:15), <anonymous>:4:206)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:9000/bower_components/angular/angular.js:23371:17)
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:15878:28)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:15978:25)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/bower_components/angular/angular.js:23376:23)
    at HTMLButtonElement.n.event.dispatch (http://localhost:9000/bower_components/jquery/dist/jquery.min.js:3:6444)
    at HTMLButtonElement.n.event.add.r.handle (http://localhost:9000/bower_components/jquery/dist/jquery.min.js:3:3219)
```

Code I used:
```
    /**
     *
     */
    module.service('AuthService', function($http, auth, store, $location) {

        var service = {};

        service.login = function () {
            auth.signin({}, function (profile, token) {
                // Success callback
                store.set('profile', profile);
                store.set('token', token);
                $location.path('/');
            }, function () {
                // Error callback
            });
        };
        service.logout = function () {
            auth.signout();
            store.remove('profile');
            store.remove('token');
        };

        return service;

    });

    /**
     *
     */
    module.controller('LoginController', function ($scope, AuthService) {
        $scope.login = AuthService.login;
        $scope.logout = AuthService.logout;
    });
```

Auth0 includes:

```
<!-- We use client cookies to save the user credentials -->
<script src="//code.angularjs.org/1.2.16/angular-cookies.min.js"></script>

<!-- Auth0 Lock script and AngularJS module -->
<script src="//cdn.auth0.com/js/lock-7.5.min.js"></script>
<!-- angular-jwt and angular-storage -->
<script type="text/javascript" src="//cdn.rawgit.com/auth0/angular-storage/master/dist/angular-storage.js"></script>
<script type="text/javascript" src="//cdn.rawgit.com/auth0/angular-jwt/master/dist/angular-jwt.js"></script>

<script src="//cdn.auth0.com/w2/auth0-angular-4.js"> </script>
```

Markup:

```
<li ng-controller="LoginController">
    <button ng-click="login()">Login</button>
    <button ng-click="logout()">Logout</button>
</li>
```

**Comment by jmls** [comment]
I've just hit this problem as well - however it doesn't seem to be minimization that is causing the problem
![image](https://cloud.githubusercontent.com/assets/929523/13669965/e5dcc6da-e6be-11e5-99aa-803886bd4edf.png)

as you can see, the loaded src is not minified - 

![image](https://cloud.githubusercontent.com/assets/929523/13669996/12eb8fee-e6bf-11e5-9c9a-f86f27f1783f.png)

**Comment by peterholcomb** [comment]
+1 to what jmls is seeing.  We also just started seeing this.

**Comment by peterholcomb** [comment]
@mgonto Any chance you are getting other reports of this happening?  This just started happening to an app of ours.

**Comment by mgonto** [comment]
Hey @ntotten will check abs follow up :).
—gonto

**Comment by phamtuananh791994** [comment]
![screenshot from 2016-03-21 10 19 09](https://cloud.githubusercontent.com/assets/14154992/13910021/68ee223e-ef4e-11e5-9dd0-b29cf2dcc34a.png)
I have the same issues. Can you please fix it immediately. Thanks you

**Comment by mpaul31** [comment]
i too am having problems. if i do not minify auth0.js all is good

**Comment by GregaVrbancic** [comment]
Hi guys! Is there any update regarding this issue?

**Comment by Soenneker** [comment]
I'm also running into this problem after minification of the JavaScript library 'auth0-lock' version 9.0.1 and 9.0.4.

**Comment by jmls** [comment]
aaaarrrgggghhhhhhh

just got this again

```
auth0-angular.js:685 Uncaught ReferenceError: t is not defined
```

this is the order of my scripts

  <script src="../bower_components/auth0-lock/build/auth0-lock.js"></script>
  <script src="../bower_components/auth0.js/build/auth0.js"></script>
  <script src="../bower_components/auth0-angular/build/auth0-angular.js"></script>
  <script src="../bower_components/angular-jwt/dist/angular-jwt.js"></script>
  <script src="../bower_components/a0-angular-storage/dist/angular-storage.js"></script>

auth0.js@7.0.2
auth0-lock@9.2.1
auth0-angular@4.2.0

*please* *please* could someone get a resolution for this - it's driving me nuts

**Comment by christiannwamba** [comment]
@jmls 👍 Thanks a lot. Got that. Will fix now

**Comment by jmls** [comment]
good news - I assume that you will be making a new release so that we can pull this fix ? It's borking in all my qa systems atm :(

**Comment by christiannwamba** [comment]
Yeah. It should be good on npm and bower now. CDN will be available soon (`v4.2.1`)

**Comment by jmls** [comment]
thanks

**Comment by krokhale** [comment]
Breaking on minifying continues to be an issue for me and is forcing me to switch to Firebase web ui now. 

To recreate the issue:

Generate a vanilla app using: https://github.com/angular-fullstack/generator-angular-fullstack and add auth0-angular and create a build which minifies assets.

These are the three modules i include in the angular app:

'auth0',
'angular-storage',
'angular-jwt'

**Comment by christiannwamba** [comment]
Hi @krokhale I am working to get this resolved and that is why the issue is still open. Apologies for the inconveniences

**Comment by christiannwamba** [comment]
@krokhale could you let me know the versions of the library you are using especially that of  auth0-angular. From the three modules you stated, `auth0-angular` is not included. If possible, your bower.json will be of great help.

**Comment by krokhale** [comment]
Thanks! Here it is:

"a0-angular-storage": "^0.0.15",
"angular-jwt": "^0.0.9",
"auth0-angular": "^4.1.0"

**Comment by christiannwamba** [comment]
Hi @krokhale 

I just tested with "auth0-angular": "~4.2.1" and after minifying, everything works fine using [generator-angular-fullstack](https://github.com/angular-fullstack/generator-angular-fullstack). When exactly in the application do you experience an error and what error do get?

Thank you

**Comment by krokhale** [comment]
- I have pushed in a test app to: https://github.com/krokhale/auth0-test

- I was wondering if jwt or storage modules were not minifying as expected. But it ends up that after i minify it without those, there is still errors in the config block.

- Check out line 27 in client/app/app.js  If you uncomment out authProvider callback and minify it, it breaks down again. I am guessing it has something to do with 'authProvider' in your code that breaks things.

- To minify locally and see if it works run: grunt serve:dist --force

- Let me know if any questions.

**Comment by christiannwamba** [comment]
I just tested with your repo and it works fine. Can you annotate the config as you are minifying:

```js
.config(['$routeProvider', '$locationProvider', 'authProvider', function($routeProvider, $locationProvider, authProvider) {
    $routeProvider
      .otherwise({
        redirectTo: '/'
      });

    authProvider.init({
      domain: 'DOMAIN.auth0.com',
      clientID: "CID",
      loginUrl: '/'
    });

    $locationProvider.html5Mode(true);
  }])
```

**Comment by krokhale** [comment]
Just annotated and few changes for callbacks on authProvider.

-  It works, IF there are no callbacks (loginSuccess and loginFailure) on authProvider. Check out line 28-42 in app.js

- You should be able to pull in the changes and run this replicate it : grunt serve:dist --force

**Comment by christiannwamba** [comment]
Still works on my end. Kindly clone my own repo and retry let's see how that goes. The `loginSuccess` is added to it.

**Comment by christiannwamba** [comment]
Could you create a support ticket here: https://auth0.com/support
I will assist you from there as this is more of implementation rather than an issue with the SDK

**Comment by krokhale** [comment]
Thanks, this is all set. The annotation works. Though i am not sure why we would need to annotate explicitly, should't the SDK handle all that already?

**Comment by christiannwamba** [comment]
Annotation is just for the given app. The SDK exposes API and doesn't know how what is exposed is used. Generally for all servicer/providers not just this SDK, you have to annotate manually or use something like ngAnnontate to automate it. Thanks

**Comment by krokhale** [comment]
- The generator by default does annotate. And i have not had an instance of using a module and having to annotate manually except in this case. This is present in the Gruntfile in your repo as well:

<img width="738" alt="screen shot 2016-06-09 at 2 41 39 pm" src="https://cloud.githubusercontent.com/assets/173148/15924580/756c397e-2e50-11e6-9b35-71520598183f.png">

- Though this resolves my issue for now, but i think there is something funky going on with the SDK which does not play well with ngAnnotate. Since if we remove the manual annotations, it does not minify well.

**Comment by ntotten** [comment]
I want to investigate this a little more to see if there is anything we can do to improve this.

**Comment by Soenneker** [comment]
Just so you're aware, this is happening in the non-angular version of Auth0 too.

**Comment by schwer** [comment]
I see this issue manifested when the user enters their email/password into my login form. Instead of using the popup method as specified through the signin api, the callback method is used, which ultimately yields an error. The error goes away when I supply
```javascript
compress: {
  keep_fargs: true
}
```
to the uglify-js module that minifies the auth0-angular codebase.

**Comment by chocmah** [comment]
i ran into the same issue, was able to make it work by adding 'Auth0' to my signin call.

` auth.signin({
        connection: 'Username-Password-Authentication',
        username: user,
        password: pass,
        authParams: {
          scope: 'openid name email',
        },
      }, (profile, idToken, accessToken, state, refreshToken) => {
        store.set('profile', profile);
        store.set('id_token', idToken);
        onLoginSuccess();
      }, (error) => {
        onLoginFailed();
      },
      'Auth0')`

i was using Uglyfy with webpack 

`        new webpack.optimize.UglifyJsPlugin({
          sourceMap: true,
        })`

**Comment by idanb11** [comment]
I have the same error too:

```
Uncaught TypeError: Cannot read property 'parseOptions' of undefined
```

I'm using the following scripts:
```js
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js"></script>
<script type="text/javascript" src="//cdn.auth0.com/js/lock-9.2.2.min.js"></script>
<script type="text/javascript" src="//cdn.auth0.com/w2/auth0-angular-4.min.js"></script>
```

**Comment by msheanimate** [comment]
Has this been resolved still running into the same issue.  Cant say that i have had a good experience using your tool
