### ISSUE TITLE
Mocha Unit test crashes on winchan...

### ISSUE THREAD

**Issue by RobbertWolfs** [auth0/auth0-angular#212]
I'm trying to use auth0-angular in my angular project and it works..
But when I try to run my unit tests, my tests crashes..

I start my mocha tests using the following gulp task..

    gulp.task('test', Object.assign(() => {
       return gulp
            .src([
                './test/spec.helper.mocha.js',
                'app/**/*.spec.js',
                'server/**/*.spec.js',
                'test/samples/*.spec.js',
            ], { read: false })
            .pipe(mocha({
                reporter: 'mocha-circleci-reporter',      // spec, nyan, ...
                env: { BABEL_ENV: 'node' },               // to ignore scss imports
               compilers: 'js:babel-core/register',
            }));
    }, {
        description: 'Running unit tests with mocha',
    }));

I always get the following error...
Does anyone has a suggestion?
Do I need to include something before running my mocha tests or ?

    /Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/winchan/winchan.js:28
        else if (ua.indexOf("Trident") > -1) {
                   ^

    TypeError: Cannot read property 'indexOf' of undefined
        at isInternetExplorer (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/winchan/winchan.js:28:16)
        at /Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/winchan/winchan.js:81:14
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/winchan/winchan.js:297:3)
        at Module._compile (module.js:398:26)
        at Module._extensions..js (module.js:405:10)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:136:7)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/auth0-js/index.js:14:25)
        at Module._compile (module.js:398:26)
        at Module._extensions..js (module.js:405:10)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:136:7)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/auth0-lock/index.js:15:13)
        at Module._compile (module.js:398:26)
        at Module._extensions..js (module.js:405:10)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:136:7)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/app/index.js:31:18)
        at Module._compile (module.js:398:26)
        at loader (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:128:5)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:138:7)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (spec.helper.mocha.js:22:1)
        at Module._compile (module.js:398:26)
        at loader (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:128:5)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/babel-register/lib/node.js:138:7)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at /Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/lib/mocha.js:219:27
        at Array.forEach (native)
        at Mocha.loadFiles (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/lib/mocha.js:216:14)
        at Mocha.run (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/lib/mocha.js:468:10)
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/bin/_mocha:403:18)
        at Module._compile (module.js:398:26)
        at Object.Module._extensions..js (module.js:405:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Function.Module.runMain (module.js:430:10)
        at startup (node.js:141:18)
        at node.js:1003:3
    [15:22:50] 'test' errored after 2.01 s
    [15:22:50] Error in plugin 'gulp-spawn-mocha'
    Mocha exited with code 1

**Comment by RobbertWolfs** [comment]
I found why ua was 'undefined', ua was the variable for navigator.useragent and I used jsdom for my mocha tests.. Jsdom is a virtual DOM so it doesn't have a useragent...

No I have updated my gulp command to the following: 
I updated the line of the compilers..

    gulp.task('test', Object.assign(() => {
        return gulp
            .src([
                './test/spec.helper.mocha.js',
                'app/**/*.spec.js',
                'server/**/*.spec.js',
                'test/samples/*.spec.js',
            ], { read: false })
            .pipe(mocha({
                reporter: 'mocha-circleci-reporter',      // spec, nyan, ...
                env: { BABEL_ENV: 'node' },               // to ignore scss imports
                compilers: 'js:babel-core/register,js:packageify,,ejs:ejsify',
            }));
    }, {
        description: 'Running unit tests with mocha',
    }));

But now I get the following error :

$ gulp test
    [16:06:06] Requiring external module babel-register
    [16:06:08] Using gulpfile ~/git/pelckmans/pakket-p/gulpfile.babel.js
    [16:06:08] Starting 'test'...
    /Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/bin/_mocha:301
      if (mod[0] == '.') mod = join(process.cwd(), mod);
             ^

    TypeError: Cannot read property '0' of undefined
        at /Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/bin/_mocha:301:10
        at Array.forEach (native)
        at Object.<anonymous> (/Users/robbertwolfs/git/pelckmans/pakket-p/node_modules/mocha/bin/_mocha:296:19)
        at Module._compile (module.js:398:26)
        at Object.Module._extensions..js (module.js:405:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Function.Module.runMain (module.js:430:10)
        at startup (node.js:141:18)
        at node.js:1003:3
    [16:06:08] 'test' errored after
    [16:06:08] Error in plugin 'gulp-spawn-mocha'
    Mocha exited with code 1


I also need to add packageify to the compilers for .js but I don't now how..
Same issue as https://github.com/auth0/lock/issues/314

Anyone a solution?

**Comment by christiannwamba** [comment]
Hey

This is tagged invalid as it is not entirely related to this SDK but I think you might need to bundle your app before testing. Have you tried that?
