### ISSUE TITLE
Error: Popup closed

### ISSUE THREAD

**Issue by weilinzung** [auth0/auth0-angular#270]
"@auth0/auth0-angular": "^1.8.2"
 "@angular/core": "~13.0.0"

When opening the login with `this.auth.loginWithPopup()`, but just close it would have the below error.

```
core.mjs:6495 ERROR Error: Uncaught (in promise): Error: Popup closed
Error: Popup closed
    at n [as constructor] (auth0-spa-js.production.esm.js:15:49849)
    at new n (auth0-spa-js.production.esm.js:15:50522)
    at auth0-spa-js.production.esm.js:15:50971
    at __trace__ (bugsnag.js:2642:30)
    at timer (zone.js:2561:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25840:33)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at invokeTask (zone.js:487:1)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25840:33)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
```

**Comment by frederikprijck** [comment]
Hey,

That's an expected error that is being thrown, as we want to notify you that the popup was closed. You want to catch this error and act accordingly.

Thanks.

**Comment by weilinzung** [comment]
hi @frederikprijck  thanks for replying. any doc about that method about how to catch that error in angualr?
