### ISSUE TITLE
Consent required error

### ISSUE THREAD

**Issue by spaghettifunk** [auth0/auth0-angular#343]
Hi! I followed the Readme and the [tutorial](https://auth0.com/docs/quickstart/spa/angular/02-calling-an-api) for creating the Login/Logout buttons for my application and calling an API. Once I'm trying to call the `Management APIs` to get the user information, I keep receiving the following error in the Chrome console

```
Error: Consent required
    at new n (auth0-spa-js.production.esm.js:1:52144)
    at n.fromPayload (auth0-spa-js.production.esm.js:1:52288)
    at r (auth0-spa-js.production.esm.js:1:94739)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26218:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
```

this is the version of Angular I have

```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.1.3
Node: 16.14.2
Package Manager: npm 8.18.0
OS: darwin arm64

Angular: 14.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.1.3
@angular/cli                    14.1.3
@schematics/angular             14.1.3
rxjs                            7.5.6
typescript                      4.7.4
```
and I have the latest version of the auth0 package.

My code snippet is exactly the same as the tutorial. I report it here just in case I'm missing something

```
// app.module.ts

@NgModule({
  declarations: [
    AppComponent, NotfoundComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    AuthModule.forRoot({
      domain: 'DOMAIN_HERE,
      clientId: 'CLIENT_ID',
      audience: 'https://AUDIENCE.eu.auth0.com/api/v2/',
      httpInterceptor: {
        allowedList: [
          {
            uri: 'https://AUDIENCE.eu.auth0.com/api/v2/*',
            tokenOptions: {
              // The attached token should target this audience
              audience: 'https://AUDIENCE.eu.auth0.com/api/v2/',
              // The attached token should have these scopes
              scope: 'read:current_user'
            }
          },
        ]
      }
    }),
  ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AuthHttpInterceptor, multi: true },
  ],
  bootstrap: [AppComponent]
})
```

and now the API call

```
ngOnInit(): void {
    this.authService.error$.subscribe(error => {
      console.log(error);
    });

    this.authService.user$
      .pipe(
        concatMap((user) =>
          // Use HttpClient to make the call
          this.http.get(
            encodeURI(`https://AUDIENCE.eu.auth0.com/api/v2/users/${user?.sub}`)
          )
        ),
        map((x: any) => x.app_metadata),
        tap((meta) => {
         console.log(meta);
        })
      )
      .subscribe();
  }
```

Looking in the Logs page of Auth0 I see the following

| Type  | Description |
| ------------- | ------------- |
| Failed Silent Auth | Consent Required  |
| Success Silent Auth | Successful silent authorization  |
| Success Exchange  | Authorization Code for Access Token |

I checked many times and I don't have the `Skip Consent` Toggle in the Management APIs turned on. Thank you in advance for any pointer to solve this.

**Comment by frederikprijck** [comment]
Hello,

Can you pass`'read:current_user'` as `scope` when constructing the module?

```
AuthModule.forRoot({
      domain: 'DOMAIN_HERE,
      clientId: 'CLIENT_ID',
      audience: 'https://AUDIENCE.eu.auth0.com/api/v2/',
      scope: 'read:current_user'
      httpInterceptor: {
        allowedList: [
          {
            uri: 'https://AUDIENCE.eu.auth0.com/api/v2/*',
            tokenOptions: {
              // The attached token should target this audience
              audience: 'https://AUDIENCE.eu.auth0.com/api/v2/',
              // The attached token should have these scopes
              scope: 'read:current_user'
            }
          },
        ]
      }
    }),
```
Can you let me know if it changes anything?

**Comment by spaghettifunk** [comment]
Hi! Sorry for the delay. I tried again and it still returns the error. The workaround I have is that instead of calling the Management API directly from the frontend, I use my backend to call and return the response to the frontend. In this way the error is gone. But besides this, I'm not sure what it can be 😞

**Comment by frederikprijck** [comment]
Can you please provide a minimal reproduction of the issue? That way, we can look t it more carefully to try and determine whats causing it.

**Comment by spaghettifunk** [comment]
I tried to replicate it and I can't anymore. I will close the issue and if I manage to replicate it will post it here again. Thanks for the help 😄
