### ISSUE TITLE
Getting intermittent error when logging in

### ISSUE THREAD

**Issue by djwatson82** [auth0/auth0-angular#624]
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am following the suggested login flow documented, but I am intermittently getting an error after login (with redirect) that makes it appear that the user did not log in. Subscribing to `authService.error$` returns the following error only when this issue occurs:

```
Error: Compilation failed: Cannot overwrite `user` model once compiled.
    at te.<anonymous> (auth0-spa-js.production.esm.js:1:32881)
    at Generator.next (<anonymous>)
    at chunk-DHZM6WDG.js?v=b79609c9:77:61
    at new ZoneAwarePromise (polyfills.js:2118:23)
    at __async (chunk-DHZM6WDG.js?v=b79609c9:61:10)
    at te.handleRedirectCallback (auth0-spa-js.production.esm.js:1:32342)
    at auth0-auth0-angular.mjs:491:41
    at Observable2._subscribe (defer.js:5:19)
    at Observable2._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
```

This error is also reproducible with the angular sample app, and the angular-spa-js sample app.

### Reproduction

1. On button click, call `loginWithRedirect`. Make sure to be subscribing to error$.
2. Login as usual through auth0 UI.
3. Intermittently, when redirected back to out application, the above error is throw and the user is not authenticated (isAuthenticated$ will return false).

### Additional context

- Using `@angular` version 18 (18.0.5), but have seen this issue with all version of angular from 15 through 18.
- Using `@auth0/auth0-angular` version 2.2.3 (recently updated, but was getting the issue prior to update).

### auth0-angular version

2.2.3

### Angular version

18.0.5

### Which browsers have you tested in?

Chrome, Edge, Safari, Firefox

**Comment by djwatson82** [comment]
This issue was related to an error in our Actions flow for post-login, but was surfacing as an error in the app.
